version: '2.0'

services:
    postgres:
      build: .
      container_name: postgres-scrabble-helper
      ports:
        - "5431:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=scrabble_helper
